Draft: Phonon thermostat
NQCD/NQCDynamics.jl pull request #349
Opened 2024-07-22 08:54 UTC by Alexsp32

Fixes #73

2025-02-17 10:58 UTC, Alexsp32 commented
I still want to rename `Thermostat`s to something that describes them better. Maybe just `Temperature`, but then it makes it a bit more unclear when one of those is needed and when it's not. To be discussed in meeting today.

2025-02-17 11:27 UTC, reinimaurer1 commented
Thermostat is pretty self explanatory, is it not? What about other ensembles? E.g. barostats?

2025-02-18 17:41 UTC, reinimaurer1 commented on Project.toml
> +julia = "≥1.9"
do we now require JL>=1.9 throughout? we should be careful not to bump any higher until we have carefully tested

2025-02-18 17:45 UTC, reinimaurer1 commented on docs/src/NQCModels/combining_models.md
> +However, a model for a potential energy surface does not and should not be able to provide e.g. an electronic friction tensor.
the way how you phrased this is ok. the same isn't 100% true for a hamiltonian model. there you would want the friction evaluation capabilities inside. As we've discussed, this won't be a problem in the future.

2025-02-18 17:48 UTC, reinimaurer1 commented on docs/src/NQCModels/neuralnetworkmodels.md
> +      A more direct interface for the use of MACE models is now available. @Alex link to example page and API docs here.
is "@Alex link to example page and API docs here." still meant to be there?

2025-02-18 17:57 UTC, reinimaurer1 commented on docs/src/dynamicssimulations/dynamicssimulations.md
> +If different parts of the simulated system should be affected by different effective temperatures, a `Vector` of [`Thermostat`](@ref)s can be passed as the temperature argument.
you probably want to include the caveat that the thermostats should not simultaneously act on two atoms. They should only act on exclusive subdomains of the atoms of the system

2025-02-18 17:57 UTC, reinimaurer1 commented on docs/src/dynamicssimulations/dynamicssimulations.md
> +If different parts of the simulated system should be affected by different effective temperatures, a `Vector` of [`Thermostat`](@ref)s can be passed as the temperature argument.
otherwise their effect and the random forces aren't additive

2025-02-18 18:09 UTC, reinimaurer1 commented on docs/src/examples/mdef_multithermostat.md
> +The two-temperature model (TTM) is a system of two coupled differential equations that describe the time evolution of the electronic and lattice temperatures, $T_{el}$ and $T_{ph}$. In this work, lat
"heat transport" instead of "heat diffusion"

2025-02-18 18:12 UTC, reinimaurer1 commented on docs/src/examples/mdef_multithermostat.md
> +	mobile_atoms::Vector{Int}=18:56, # Freeze the bottom two layers
the comment should say "set top X layers as mobile, leave bottom two layers frozen" because that is what the command does.

2025-02-18 18:13 UTC, reinimaurer1 commented on docs/src/examples/mdef_multithermostat.md
> +phonon_thermostat = Temperature(T_el_function, phononic_friction)
shouldn't this be "T_ph_function"?

2025-02-18 18:13 UTC, reinimaurer1 commented on docs/src/examples/mdef_multithermostat.md
> +phonon_thermostat = Temperature(T_el_function, phononic_friction)
if the phonon thermostat follows a T profile

2025-02-18 18:46 UTC, reinimaurer1 commented on src/Analysis/diatomic.jl
> +function surface_distance_condition(x::AbstractArray, indices::Vector{Int}, simulation::AbstractSimulation; surface_distance_threshold=5.0 * u"Å", surface_normal=Float64[0, 0, 1])
this function looks rather messy and hard to read. probably because functions take other functions as arguments. any chance that this can be improved in terms of readability?

2025-02-18 18:49 UTC, reinimaurer1 commented on src/Analysis/diatomic.jl
> +    if au_to_ang(molecule_position - highest_z) * u"Å" ≥ surface_distance_threshold
does this function assume that your surface_distance_threshold condition has been given in Angstrom? why does it do "au_to_ang"* u"Ang"?

2025-02-18 19:02 UTC, reinimaurer1 commented on src/DynamicsOutputs.jl
> +Distance is defined by the projected distance from the highest non-adsorbate atom along the surface normal.
might need a better doc string. explain that all atoms that aren't adsorbate_indices are considered for the calculation of the surface.

2025-02-18 19:09 UTC, reinimaurer1 commented on src/NQCDistributions-convenience.jl
> +Add-on functions for NQCDistributions to make generating distributions more convenient.
please expand on this. this basically is just a wrapper to accommodate `mobileatoms` and the ability to freeze atoms

2025-02-18 19:10 UTC, reinimaurer1 commented on src/NQCDistributions-convenience.jl
> +Add-on functions for NQCDistributions to make generating distributions more convenient.
adjust docstring below, not here at the top, although it might be useful to state what functions should go here and what stuff should go straight into NQCDistributions (basically anything that is a Distribution)

2025-02-18 19:11 UTC, reinimaurer1 commented on src/simulations.jl
> +            throw(DomainError(temperature, "Every atom must have a Thermostat applied to it."))
why is is a requirement that every atom must have a thermostat? you could also only apply a thermostat to a subset of atoms.

2025-02-18 19:13 UTC, reinimaurer1 commented on src/simulations.jl
> +**If you don't need to apply different temperatures to different parts of your Simulation, supply the Simulation with a number or function instead.**
you mean "assign the Temperature argument of `Simulation` to be a number or a function"

2025-02-18 19:14 UTC, reinimaurer1 commented on src/simulations.jl
> +`value`: A temperature function. This can be a Number type for constant temperatures, or a function taking the time in Unitful `u"ps"` as input and giving a temperature in Unitful `u"K"` as output.
is it a requirement to define time in u"ps"?

2025-02-18 19:15 UTC, reinimaurer1 commented on src/simulations.jl
> +`indices`: Indices of the atoms to apply this thermostat to. Can be a range of indices, a single `Int`, or a `Vector{Int}`.
sentences ending with prepositions /= cool

"Indices of atoms to which this thermostat is applied"

2025-02-18 19:17 UTC, reinimaurer1 commented on src/simulations.jl
> +function get_temperature(thermostats::Vector{<:Temperature}, t=0u"fs")
as this provides a list of temperatures, should it not be called "get_temperatures"? (obviously I am against that, but please add a doc string to the function to elaborate)

2025-02-18 19:18 UTC, reinimaurer1 commented on test/Core/simulations.jl
> +    # Init thermostat with unitful quality
quantity?

2025-02-18 19:21 UTC, reinimaurer1 commented on ext/MACEModelsext.jl
I don't quite understand why this is necessary for batch evaluation. maybe you can explain offline

2025-02-18 19:22 UTC, reinimaurer1 commented on src/Analysis/postprocess.jl
> +    apply_output_functions(sol::FakeSolution, output_functions; savetime::Bool=true)
sooo useful!

2025-02-18 19:25 UTC, reinimaurer1 requested changes
I left lots of minor comments, mostly related to docs. There is one bit I don't quite understand, but we can discuss offline at some point.

2025-02-19 15:34 UTC, Alexsp32 commented
> Thermostat is pretty self explanatory, is it not? What about other ensembles? E.g. barostats?

Yes, however the Integrator chosen as part of the `DynamicsMethod` decides the implementation of the thermostat, while these structs just store a temperature and which parts of the system experience it.

2025-02-19 15:35 UTC, Alexsp32 commented on Project.toml
> +julia = "≥1.9"
Yes, this is needed for Package extensions, plus v1.10 is now LTS release.

2025-02-19 15:38 UTC, Alexsp32 commented on docs/src/NQCModels/neuralnetworkmodels.md
> +      A more direct interface for the use of MACE models is now available. @Alex link to example page and API docs here.
Fixed

2025-02-19 15:42 UTC, Alexsp32 commented on docs/src/dynamicssimulations/dynamicssimulations.md
> +If different parts of the simulated system should be affected by different effective temperatures, a `Vector` of [`Thermostat`](@ref)s can be passed as the temperature argument.
Fixed

2025-02-19 15:54 UTC, Alexsp32 commented on src/Analysis/diatomic.jl
> +    if au_to_ang(molecule_position - highest_z) * u"Å" ≥ surface_distance_threshold
Updated to require distance in au

2025-02-19 15:58 UTC, Alexsp32 commented on src/NQCDistributions-convenience.jl
> +Add-on functions for NQCDistributions to make generating distributions more convenient.
We discussed this in a previous PR. Since NQCDistributions can't be made to require NQCDynamics.jl, this is the best way of making functions from NQCDistributions work with NQCDynamics objects.

2025-02-19 16:00 UTC, Alexsp32 commented on src/simulations.jl
> +            throw(DomainError(temperature, "Every atom must have a Thermostat applied to it."))
The idea is to make the behaviour unambiguous. If a temperature isn't set, should no thermostat be applied? Should a default temperature be used? 

This way a conscious decision is necessary for all atoms in the system, and not applying a thermostat can be achieved by setting a temperature of 0.

2025-02-19 16:03 UTC, Alexsp32 commented on src/simulations.jl
> +`value`: A temperature function. This can be a Number type for constant temperatures, or a function taking the time in Unitful `u"ps"` as input and giving a temperature in Unitful `u"K"` as output.
Yes, this is how NQCDynamics requires it for some reason.

2025-02-19 16:05 UTC, Alexsp32 commented on src/simulations.jl
> +function get_temperature(thermostats::Vector{<:Temperature}, t=0u"fs")
No, this is a multiple dispatch Method which Simulations use to update the temperature value.

2025-02-19 16:06 UTC, Alexsp32 commented on ext/MACEModelsext.jl
Discussed in person

2025-02-19 16:08 UTC, Alexsp32 commented on src/Analysis/postprocess.jl
> +    apply_output_functions(sol::FakeSolution, output_functions; savetime::Bool=true)
To be continued in #335

2025-02-19 16:11 UTC, Alexsp32 commented
@reinimaurer1 ready for re-review

2025-02-19 16:32 UTC, reinimaurer1 approved these changes
thanks for the changes. all good

2025-02-19 16:37 UTC, merged